set echo on
DROP USER DP_ORACLE CASCADE;
CREATE USER "DP_ORACLE" PROFILE "DEFAULT" IDENTIFIED BY "D3_0R4CL3" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
grant connect to DP_ORACLE;
grant unlimited tablespace to DP_ORACLE;
grant sysdba to DP_ORACLE;
grant select any table to DP_ORACLE;
grant select_catalog_role to DP_ORACLE;
alter system set control_file_record_keep_time=45 scope=both;
alter system set backup_tape_io_slaves=true scope=spfile;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CONFIGURE CONTROLFILE AUTOBACKUP ON;
CONFIGURE DEVICE TYPE 'SBT_TAPE' PARALLELISM 2 BACKUP TYPE TO BACKUPSET;
CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 30 DAYS;
CONFIGURE ARCHIVELOG DELETION POLICY TO BACKED UP 1 TIMES TO SBT;
CONFIGURE BACKUP OPTIMIZATION ON;
CONFIGURE DEFAULT DEVICE TYPE TO SBT;
CONFIGURE CONTROLFILE AUTOBACKUP FORMAT FOR DEVICE TYPE SBT TO 'CONTROLFILE_BKUP_%D_%F'; 


FFBBEEBBQGBBBEBBDGBBFEBBEFBBNFBBEEBB 

EXEC dbms_workload_repository.drop_snapshot_range(20396,20414,4207929573);


CREATE USER "DBSNMP" IDENTIFIED BY "Gen3.2016" DEFAULT TABLESPACE "SYSAUX" TEMPORARY TABLESPACE "TEMP" account unlock;

CREATE OR REPLACE PUBLIC SYNONYM "DBMS_OBFUSCATION_TOOLKIT" FOR "SYS"."DBMS_OBFUSCATION_TOOLKIT"

CREATE USER "ADMIN_SIS" IDENTIFIED BY VALUES '879769E97EC1B44B' DEFAULT TABLESPACE "SIS_DAT" TEMPORARY TABLESPACE "TEMP"
